Models/ApplicationDB.cs
using Microsoft.EntityFrameworkCore;

namespace ProductsDB.Models
{
    public class ApplicationDB : DbContext
    {
        public ApplicationDB(DbContextOptions<ApplicationDB> options)
           : base(options)
        {
            //this.Database.EnsureDeleted();
            //this.Database.EnsureCreated();
        }
        public DbSet<Product> Products { get; set; }
        public DbSet<Category> Categories { get; set; }
    }
}

Models/Category.cs
namespace ProductsDB.Models
{
    public class Category
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
    }
}

Models/JoinedData.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace ProductsDB.Models
{
    [NotMapped]
    public class JoinedData
    {
        public string ProductName {  get; set; }
        public string ProductDescription { get; set; }
        public string CategoryName { get; set; }
    }
}

Models/Product.cs
namespace ProductsDB.Models
{
    public class Product
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int CategoryId { get; set; }
    }
}

Pages/AddToDB.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using ProductsDB.Models;
using ProductsDB.Services;

namespace ProductsDB.Pages
{
    public class AddToDBModel : PageModel
    {
        ApplicationDB context { get; set; }
        [BindProperty]
        public Product newProduct { get; set; }
        [BindProperty]
        public Category newCategory { get; set; }
        [BindProperty]
        public List<Product> products { get; set; } = new();
        [BindProperty]
        public List<Category> categories { get; set; } = new();

        public AddToDBModel(ApplicationDB applicationDB) 
        {
            context = applicationDB;
        }   
        public void OnGet()
        {
            products = ProductsServices.GetProducts(context);
            categories = ProductsServices.GetCategories(context);
        }

        public IActionResult OnPostSaveProduct(Product newProduct)
        {
            ProductsServices.AddProduct(context, newProduct);
            return RedirectToAction("Get");
        }

        public IActionResult OnPostSaveCategory(Category newCategory)
        {
            ProductsServices.AddCategory(context, newCategory);
            return RedirectToAction("Get");
        }
    }
}

Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Newtonsoft.Json;
using ProductsDB.Models;
using ProductsDB.Services;

namespace ProductsDB.Pages
{
    public class IndexModel : PageModel
    {
        ApplicationDB context { get; set; }
        
        public List<JoinedData> allProducts, productsByCategory;

        public IndexModel(ApplicationDB applicationDB)
        {
            context = applicationDB;
        }

        public void OnGet()
        {
            allProducts = ProductsServices.GetJoinedData(context);
            productsByCategory = ProductsServices.GetJoinedData(context, 1);
        }
    }
}

Pages/AddToDB.cshtml
@page
@using ProductsDB.Models
@model ProductsDB.Pages.AddToDBModel
@{
}
<form method="post">
    <div class="row pt-2">
        Данные продукта
    </div>
    <div class="row pt-2 mb-5">
        <div class="col-3">
            <input type="text" class="form-control" asp-for="newProduct.Name" />
        </div>
        <div class="col-4">
            <input type="text" class="form-control" asp-for="newProduct.Description" />
        </div>
        <div class="col-2">
            <input type="number" class="form-control" asp-for="newProduct.CategoryId" />
        </div>
        <div class="col-1 d-print-none">
            <input type="submit" value="+" asp-page-handler="SaveProduct" />
        </div>
    </div>
</form>
<form method="post">
    <div class="row pt-2">
        Данные категории
    </div>
    <div class="row pt-2 mb-5">
        <div class="col-3">
            <input type="text" class="form-control" asp-for="newCategory.Name" />
        </div>
        <div class="col-4">
            <input type="text" class="form-control" asp-for="newCategory.Description" />
        </div>
        <div class="col-1 d-print-none">
            <input type="submit" value="+" asp-page-handler="SaveCategory" />
        </div>
    </div>
</form>

<div class="row mt-3">
    Список продуктов
</div>
@{
    foreach (Product prod in Model.products)
    {
        <div class="row">
            <div class="col-2">@prod.Name</div>
            <div class="col-2">@prod.Description</div>
            <div class="col-2">@prod.CategoryId</div>
        </div>
    }
}
<div class="row mt-3">
    Список категорий
</div>
@{
    foreach (Category cat in Model.categories)
    {
        <div class="row">
            <div class="col-2">@cat.Name</div>
            <div class="col-2">@cat.Description</div>
            <div class="col-2">@cat.Id</div>
        </div>
    }
}

Pages/Index.cshtml
@page
@using ProductsDB.Models
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<div class="container">
    <div class="row mt-3 mb-1">
        <div class="col-3">
            Выборка по всем товарам
        </div>
    </div>

    <div class="row mb-1">
        <div class="col-3">
            Продукт
        </div>
        <div class="col-3">
            Категория
        </div>
        <div class="col-2">
            Описание
        </div>
    </div>
    @{
        foreach(JoinedData jd in Model.allProducts)
        {
            <div class="row text-start border-bottom">
                <div class="col-3">
                    @jd.ProductName
                </div>
                <div class="col-3">
                    @jd.CategoryName
                </div>
                <div class="col-2">
                    @jd.ProductDescription
                </div> 
            </div>
        }
    }

    <div class="row mt-3 mb-1">
        <div class="col-3">
            Выборка по одной категории
        </div>
    </div>
    <div class="row">
        <div class="col-3">
            Продукт
        </div>
        <div class="col-3">
            Категория
        </div>
        <div class="col-2">
            Описание
        </div>
    </div>
    @{
        foreach (JoinedData jd in Model.productsByCategory)
        {
            <div class="row text-start border-bottom">
                <div class="col-3">
                    @jd.ProductName
                </div>
                <div class="col-3">
                    @jd.CategoryName
                </div>
                <div class="col-2">
                    @jd.ProductDescription
                </div>
            </div>
        }
    }
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProductsDB</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProductsDB.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-page="/Index">ProductsDB</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/AddToDB">Добавить данные</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - ProductsDB - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>